### PR TITLE
[fix] alter module assignment to project, update form view and tree view

### PR DESCRIPTION
**Pull request by anhoangphan96**
## Description

- Alter "assignment" to "project" (But the module name project is existing so the name of module i named as "learning_project")
- Update UI in form view and tree view

### Notion Task
Please include a link to the notion task that this pull request is related to.
- [GEN-414](https://www.notion.so/68233b1464534b7d82e15867c27a7986?v=0f1cba589b06435fad09ccd884ad96b1&p=3c6737cde5f34726acb85c7c124ab6c3&pm=s)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires the database schema to be updated.
- [x] This change create or update API endpoints.

### General
- [x] I have performed a self-review of my own code.
- [x] This change has been tested locally to ensure it pass acceptance criterias.
- [x] All conflicts have been resolved.

### Database Changes (if applicable)
- [ ] I have added a migration file to update the database schema.
- [x] I have updated the database schema ERD in this [link](https://drive.google.com/file/d/1PIRXgwItsAAR-MePVI0IXLRpVyzC3cU6/view?usp=sharing).
- [ ] I have log all change in the log file.
- [ ] All breaking changes have been communicated to the team and reviewed by PO/PM.

### API Changes (if applicable)
- [x] I have updated the API Spec in this [link](https://docs.google.com/document/d/1WdZVLshSQK6OIrvA4hru1lXAjbDNo5J1AguMZvRaz2g/edit?usp=drive_link).
- [ ] I have update the Postman Collection in this [link](https://www.postman.com/universal-meteor-717123/workspace/manhattan/collection/2573019-7ceeff4f-4d49-405e-8a8c-6dc813d91bad?action=share&creator=2573019).

## Notes
Any other relevant information that would help the reviewer.

### CODE REVIEW

**Review by DAN3002 — DISMISSED** [review]
LGTM

**Comment by DAN3002** [comment]
@anhoangphan96 Anh resolve các conflict giúp em nhé

**Comment by anhoangphan96** [comment]
@DAN3002  hi Đình Anh, anh có resolve conflict rồi em merge giúp anh nha

**Review by DAN3002 — APPROVED** [review]
LGTM

**Pull request merged**
