### PR TITLE
Feature/feedback ticket management

### PR DESCRIPTION
**Pull request by anhoangphan96**
## Description

- Update manifest file to fix unknow model bug,
- Add new authorization to help staff can submit response in ticket

### Notion Task
Please include a link to the notion task that this pull request is related to.
- [GEN-264](https://www.notion.so/68233b1464534b7d82e15867c27a7986?v=10575e2b484449898b0482071a4f1a35&p=a79b586a01c24f02a27c741dce0a19b2&pm=s)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires the database schema to be updated.
- [ ] This change create or update API endpoints.

### General
- [x] I have performed a self-review of my own code.
- [x] This change has been tested locally to ensure it pass acceptance criterias.
- [x] All conflicts have been resolved.

### Database Changes (if applicable)
- [ ] I have added a migration file to update the database schema.
- [ ] I have updated the database schema ERD in this [link](https://drive.google.com/file/d/1PIRXgwItsAAR-MePVI0IXLRpVyzC3cU6/view?usp=sharing).
- [ ] I have log all change in the log file.
- [ ] All breaking changes have been communicated to the team and reviewed by PO/PM.

### API Changes (if applicable)
- [ ] I have updated the API Spec in this [link](https://docs.google.com/document/d/1WdZVLshSQK6OIrvA4hru1lXAjbDNo5J1AguMZvRaz2g/edit?usp=drive_link).
- [ ] I have update the Postman Collection in this [link](https://www.postman.com/universal-meteor-717123/workspace/manhattan/collection/2573019-7ceeff4f-4d49-405e-8a8c-6dc813d91bad?action=share&creator=2573019).

## Notes
Any other relevant information that would help the reviewer.

### CODE REVIEW

**Comment by DAN3002** [comment]
@anhoangphan96 Phần task trên Notion hình như đang map sai, em đọc thì không thấy có gì liên quan và task này cũng ở **Sprint 4** rồi. Anh check lại giúp em với nhé.

**Comment by anhoangphan96** [comment]
> @anhoangphan96 Phần task trên Notion hình như đang map sai, em đọc thì không thấy có gì liên quan và task này cũng ở **Sprint 4** rồi. Anh check lại giúp em với nhé.

@DAN3002

**Comment by anhoangphan96** [comment]
@DAN3002  ơi cái PR này là anh fix bug cho module feedback ticket ở sprint 4 ấy, do hôm nay trên staging anh không vào được module feedback ticket nên có fix 1 số chổ

**Review by DAN3002 — APPROVED** [review]
LGTM

**Pull request merged**
